jobsearch/Controllers/jobdetailsdbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jobsearch.Models;

namespace jobsearch.Controllers
{
    public class jobdetailsdbController : Controller
    {
        careerhunt_jobserachEntities1 dbobj = new careerhunt_jobserachEntities1();
        // GET: jobdetailsdb
        public ActionResult jobdetailpageload()
        {
            return View();
        }
        public ActionResult jobdetailinsertclick(jobdeailinsertcls clsobj)
        {
            if (ModelState.IsValid)
            {

                clsobj.sts = "AVAILABLE";
                clsobj.compnyid = Convert.ToInt32(Session["uid"]);
                dbobj.sp_jobdetails(clsobj.compnyid, clsobj.jobtil, clsobj.jobdespn, clsobj.jobtype, clsobj.lastdate, clsobj.sts, clsobj.location, clsobj.expinyears, clsobj.salary, clsobj.skills);
                clsobj.msg = "successfully inserted";
                return View("jobdetailpageload", clsobj);
            }
            else
            {
                return View("jobdetailpageload", clsobj);

            }
        }
    }
}

jobsearch/Views/jobdetailsdb/jobdetailpageload.cshtml
@model jobsearch.Models.jobdeailinsertcls
@{
    ViewBag.Title = "jobdetailpageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>jobdetailpageload</h2>

<div>
    @using (@Html.BeginForm("jobdetailinsertclick", "jobdetailsdb", FormMethod.Post))
    {
        <div><label>Job Title</label></div>
        <div>
            @Html.TextBoxFor(m => m.jobtil)
        </div>

        <div><label>Job description</label></div>
        <div>
            @Html.TextBoxFor(m => m.jobdespn)
        </div>

        <div><label>Job type</label></div>
        <div>
            @Html.TextBoxFor(m => m.jobtype)
        </div>

        <div><label>Last Date</label></div>
        <div>
            @Html.TextBoxFor(m => m.lastdate)
        </div>


        <div><label>location</label></div>
        <div>
            @Html.TextBoxFor(m => m.location)
        </div>

        <div><label>Experiance in years</label></div>
        <div>
            @Html.TextBoxFor(m => m.expinyears)
        </div>


        <div><label>Salary</label></div>
        <div>
            @Html.TextBoxFor(m => m.salary)
        </div>

        <div><label>Skills</label></div>
        <div>
            @Html.TextBoxFor(m => m.skills)
        </div>

        <input type="submit" value="INSERT" />
        @Html.DisplayFor(m => m.msg)
    }
</div>