jobsearch/Controllers/applaycvController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jobsearch.Models;

namespace jobsearch.Controllers
{
    public class applaycvController : Controller
    {
        careerhunt_jobserachEntities1 dbobj = new careerhunt_jobserachEntities1();

        // GET: applaycv
        public ActionResult applay_pageload(int cid, int jid)
        {
            TempData["CID"] = cid;
            TempData["JID"] = jid;
          
            return View();
        }
        public ActionResult apply_click(applycls clsobj, HttpPostedFileBase file)
        {
            if (file.ContentLength > 0)
            {
                //fileupload
                string fname = Path.GetFileName(file.FileName);
                var s = Server.MapPath("~//PHS");
                string pa = Path.Combine(s, fname);
                file.SaveAs(pa);

                var fullpath = Path.Combine("~//PHS", fname);
                clsobj.cv = fullpath;
            }

            clsobj.date = DateTime.Now.ToString("yyyy-MM-dd");
            clsobj.usid = Convert.ToInt32(Session["uid"]);
            clsobj.sts = "APPLIED";
            byte[] cvbybtes = System.Text.Encoding.UTF8.GetBytes(clsobj.cv);
            dbobj.sp_apply(clsobj.usid, Convert.ToInt32(TempData["CID"]), Convert.ToInt32(TempData["JID"]), cvbybtes, clsobj.date, "applied");
            clsobj.msg = "INSERTED SUCCESFULLY";
            return View("applay_pageload", clsobj);
        }
    }
}

jobsearch/Controllers/logindbController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jobsearch.Models;

namespace jobsearch.Controllers
{
    public class logindbController : Controller
    {
        careerhunt_jobserachEntities1 dbobj = new careerhunt_jobserachEntities1();
        // GET: logindb
        public ActionResult loginpageload()
        {
            return View();
        }

        public ActionResult companyhome()
        {
            return View();
        }

        public ActionResult userhome()
        {
            return View();
        }

        public ActionResult loginclick(logincls clsobj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_LOGINCOUNTID(clsobj.uname, clsobj.passwd, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_logingetid(clsobj.uname, clsobj.passwd).FirstOrDefault();
                    Session["uid"] = uid;
                    var logtype = dbobj.sp_Logtype(clsobj.uname, clsobj.passwd).FirstOrDefault();
                    if (logtype == "company")
                    {
                        return View("companyhome");
                    }
                    else if (logtype == "USER")
                    {
                        return View("userhome");
                    }
                }
            }
            else
            {
                ModelState.Clear();
                clsobj.msg = "INVALID USername and password";
                return View("loginpageload", clsobj);
            }
            return View("loginpageload", clsobj);
        }
    }
}

jobsearch/Controllers/searchjobController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jobsearch.Models;

namespace jobsearch.Controllers
{
    public class searchjobController : Controller
    {
        careerhunt_jobserachEntities1 dbobj = new careerhunt_jobserachEntities1();
        // GET: searchjob
        public ActionResult searchjob_pageload()
        {
            return View(getdata());
        }

        private joobsearch getdata()
        {
            var joblist = new joobsearch();
            List<string> lst = new List<string>();
            var job = dbobj.sp_jobs().ToList();
            foreach (var e in job)
            {
                var jobcls = new jsearch();
                jobcls.jobid = e.job_id;
                jobcls.cmpnyid = e.company_id;
                jobcls.jobtitle = e.job_title;
                jobcls.jobdespn = e.job_description;
                jobcls.jobtype = e.job_type;
                jobcls.lastdate = e.lastdate;
                jobcls.sts = e.status;
                jobcls.lcn = e.location;
                jobcls.experience = e.experiance_in_years;
                jobcls.sal = Convert.ToInt32(e.salary);
                jobcls.skills = e.skills;

                joblist.selectjob.Add(jobcls);
                //var s = jobcls.skills;
                //lst.Add(s);
                //TempData["skills"] = string.Join(" ", lst);

            }
            return joblist;
        }
        public ActionResult searchjob_click(joobsearch clsobj)
        {
            string qry = "";
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.experience.ToString()))
            {
                qry += " and experiance_in_years like '%" + clsobj.insertse.experience + "'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.skills))
            {
                qry += " and skills like '%" + clsobj.insertse.skills + "'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.lcn))
            {
                qry += " and location like '%" + clsobj.insertse.lcn + "'";
            }
            return View("searchjob_pageload", getdata1(clsobj, qry));
        }

        public joobsearch getdata1(joobsearch clsobj, string qry)
        {
            using (var con = new SqlConnection(ConfigurationManager.ConnectionStrings["testcon"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_jobsearches", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new joobsearch();
                while (dr.Read())
                {
                    var jobcls = new jsearch();
                    jobcls.cmpnyid = Convert.ToInt32(dr["company_id"].ToString());
                    jobcls.skills = dr["skills"].ToString();
                    jobcls.experience = Convert.ToInt32(dr["experiance_in_years"].ToString());
                    jobcls.sts = dr["status"].ToString();
                    jobcls.lastdate = dr["lastdate"].ToString();
                    jobcls.lcn = dr["location"].ToString();
                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

jobsearch/Views/searchjob/searchjob_pageload.cshtml
@model jobsearch.Models.joobsearch
@{
    ViewBag.Title = "searchjob_pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Career Hunt</h2>


<div>
    @using (@Html.BeginForm("searchjob_click", "searchjob", FormMethod.Post))
    {
        <table>
            <tr>
                <td style="padding-left:8PX"><label>SKILLS</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.skills)</td>
                <td style="padding-left:8PX"><label>EXPERIENCE</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.experience)</td>
                <td style="padding-left:8PX"><label>LOCATION</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.lcn)</td>
                <td><input type="submit" value="SEARCH" /></td>
            </tr>
        </table>
    }

</div>
<div>
    @using (@Html.BeginForm("searchjob_click", "searchjob", FormMethod.Get))
    {
        if (Model != null)
        {
            <table class="table">
                <tr>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.cmpnyid)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.skills)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.experience)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.sts)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.lastdate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.insertse.lcn)
                    </th>

                </tr>
                @foreach (var item in Model.selectjob)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelitem => item.cmpnyid)
                        </td>



                        <td>
                            @Html.DisplayFor(modelitem => item.skills)
                        </td>



                        <td>
                            @Html.DisplayFor(modelitem => item.experience)
                        </td>



                        <td>
                            @Html.DisplayFor(modelitem => item.sts)
                        </td>



                        <td>
                            @Html.DisplayFor(modelitem => item.lastdate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.lcn)
                        </td>

                        <td>
                            @Html.ActionLink("APPLAY NOW", "applay_pageload", "applaycv", new { cid = item.cmpnyid, jid = item.jobid }, null)
                        </td>
                    </tr>


                }
            </table>

        }
        else
        {
            <div>
                <script>
                    alert('no data found');
                </script>
            </div>
        }


    }
    <div>
        @Html.ActionLink("back to homepage", "loginpageload", "logindb")
    </div>


</div>