jobsearch/Controllers/userinsertdbController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jobsearch.Models;

namespace jobsearch.Controllers
{
    public class userinsertdbController : Controller
    {
        careerhunt_jobserachEntities1 dbobj = new careerhunt_jobserachEntities1();
        statedistrictDB ddlcls = new statedistrictDB();
        // GET: userinsertdb
        public ActionResult userpageload()
        {
            List<stclass1> stlist = ddlcls.selectstates();
            ViewBag.selstates = new SelectList(stlist, "SID", "SNAME");
            return View();
        }
        public JsonResult Getdistrics(int stateid)
        {
            var districts = GetdistrictBystateId(stateid);
            return Json(districts, JsonRequestBehavior.AllowGet);
        }
        private List<SelectListItem> GetdistrictBystateId(int stateid)
        {
            var getdistricts = ddlcls.selectdistrict(stateid);
            var districtbystste = getdistricts.Select(a => new SelectListItem() { Value = a.DID.ToString(), Text = a.DNAME }).ToList();
            return districtbystste;
        }
        public ActionResult user_click(userinsertcls clsobj, HttpPostedFileBase file, FormCollection form)
        {
            if (ModelState.IsValid)
            {


                if (file.ContentLength > 0)
                {
                    //fileupload
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~//PHS");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);
                    

                    var fullpath = Path.Combine("~//PHS", fname);
                    clsobj.photo = fullpath;
                }
                //ddlist
                List<stclass1> stlist = ddlcls.selectstates();
                int selectedid = Convert.ToInt32(form["SID"]);
                stclass1 selecteditem = stlist.FirstOrDefault(c => c.SID == selectedid);
                clsobj.SID = selecteditem.SID;
                clsobj.SNAME = selecteditem.SNAME;//stste
                ViewBag.selstates = new SelectList(stlist, "SID", "SNAME");

                int disid = Convert.ToInt32(form["DistrictId"]);
                clsobj.DID = disid;
                //string dname = "";
                //clsobj.DNAME=dname;//district


                var maxid = dbobj.sp_selmaxregid().FirstOrDefault();
                int mid = Convert.ToInt32(maxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_userinsert(regid, clsobj.name, clsobj.age, clsobj.address, clsobj.email, clsobj.phone, clsobj.photo, clsobj.SNAME, clsobj.DID, clsobj.gender, clsobj.dob);
                dbobj.sp_logininsert(regid, clsobj.unam, clsobj.pass, "USER", "ACTIVE");
                clsobj.msg = "INSERTED SUCCESFULLY";
                return View("userpageload", clsobj);
            }
            else
            {
                List<stclass1> stlist = ddlcls.selectstates();
                ViewBag.selstates = new SelectList(stlist, "SID", "SNAME");
                return View("userpageload", clsobj);
            }


        }
    }
}

jobsearch/Views/userinsertdb/userpageload.cshtml
@model jobsearch.Models.userinsertcls
@{
    ViewBag.Title = "userpageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>userpageload</h2>

<div>
    @using (@Html.BeginForm("user_click", "userinsertdb", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div><label>name</label></div>
        <div>
            @Html.TextBoxFor(m => m.name)
        </div>


        <div><label>age</label></div>
        <div>
            @Html.TextBoxFor(m => m.age)
        </div>

        <div><label>address</label></div>
        <div>
            @Html.TextBoxFor(m => m.address)
        </div>


        <div><label>email</label></div>
        <div>
            @Html.TextBoxFor(m => m.email)
        </div>

        <div><label>phone</label></div>
        <div>
            @Html.TextBoxFor(m => m.phone)
        </div>

        <div><label>photo</label></div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>

        <div><label>state</label></div>
        <div>
            @Html.DropDownList("SID", new SelectList(ViewBag.selstates, "Value", "Text"), "select state", new { @class = "form-control", @id = "state-ddl" })
        </div>


        <div><label>districts</label></div>
        <div>
            <select id="district-ddl" class="form-control" name="DistrictId"></select>
        </div>

        <div><label>gender</label></div>
        <div>
            Male
            @Html.RadioButtonFor(m => m.gender, "male")
            Female
            @Html.RadioButtonFor(m => m.gender, "female")
        </div>

        <div><label>date of birth</label></div>
        <div>
            @Html.TextBoxFor(m => m.dob)
        </div>

        <div><label>username</label></div>
        <div>
            @Html.TextBoxFor(m => m.unam)
        </div>


        <div><label>password</label></div>
        <div>
            @Html.TextBoxFor(m => m.pass)
        </div>


        <input type="submit" value="Insert" />
        @Html.DisplayFor(m => m.msg)
    }

</div>


<script src="http://ajax.microsoft.com/ajax/jquery/jquery-1.10.2.js" type="text/javascript"></script>
<script>
    $('#district-ddl').append('<option>Select District</option>');
    $('#state-ddl').change(function () {
         var stateId = $(this).val();
         $.ajax({
             url: '@Url.Action("Getdistrics", "userinsertdb")',
             //type: 'GET',
             data: { stateId: stateId },
             //dataType: 'json',
             success: function (data) {
                 $('#district-ddl').empty();
                 $('#district-ddl').append('<option>Select District</option>');
                 $.each(data, function (index, item) {
                     $('#district-ddl').append('<option value="' + item.Value + '">' + item.Text + '</option>');
                 });
             }
         });
     });
</script>